# Camera
BOARD_GLOBAL_CFLAGS += -DMETADATA_CAMERA_SOURCE
BOARD_USE_SAMSUNG_COLORFORMAT_NV21 := true
TARGET_HAS_LEGACY_CAMERA_HAL1 := true
TARGET_PROVIDES_CAMERA_HAL := true
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true
