# Display
MAX_EGL_CACHE_KEY_SIZE := 12*1024
MAX_EGL_CACHE_SIZE := 2048*1024
NUM_FRAMEBUFFER_SURFACE_BUFFERS := 3
TARGET_FORCE_HWC_FOR_VIRTUAL_DISPLAYS := true
MAX_VIRTUAL_DISPLAY_DIMENSION := 2048
SF_START_GRAPHICS_ALLOCATOR_SERVICE := true
TARGET_CONTINUOUS_SPLASH_ENABLED := true
TARGET_USES_GRALLOC1 := true
TARGET_USES_HWC2 := true
TARGET_USES_NEW_ION_API := true

# Render
OVERRIDE_RS_DRIVER := libRSDriver_adreno.so
